# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MBPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('entity', models.PositiveIntegerField()),
                ('reference', models.PositiveIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('terminal', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
