# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugs_payments', '0002_auto_20170109_1847'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ifthenpayment',
            unique_together=set([('entity', 'reference', 'value')]),
        ),
    ]
