# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 20:11
from __future__ import unicode_literals

from django.db import migrations
import plugs_payments.fields


class Migration(migrations.Migration):

    dependencies = [
        ('plugs_payments', '0003_auto_20170109_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifthenpayment',
            name='entity',
            field=plugs_payments.fields.EntityField(),
        ),
        migrations.AlterField(
            model_name='ifthenpayment',
            name='reference',
            field=plugs_payments.fields.ReferenceField(),
        ),
    ]
