# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugs_payments', '0004_auto_20170109_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifthenpayment',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
